version: 2.1

executors:
  default:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.0

commands:
  ##
  # Cache management
  ##
  restore_packages:
    steps:
      - restore_cache:
          name: Restore npm dependencies
          key: yarn-v1-{{ checksum "yarn.lock" }}
  save_packages:
    steps:
      - run:
          name: Install npm dependencies
          command: yarn --frozen-lockfile --non-interactive
      - save_cache:
          name: Cache npm dependencies
          key: yarn-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules
  persist_data:
    steps:
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  attach_data:
    steps:
      - attach_workspace:
          at: .

jobs:
  ##
  # Commit workflow phase 1: Setup
  ##
  setup:
    executor:
      name: default
    steps:
      - checkout
      - restore_packages
      - save_packages
      - persist_data

  ##
  # Commit workflow phase 2: Lint + Test
  ##
  lint:
    executor:
      name: default
    steps:
      - checkout
      - attach_data
      - run:
          name: Run lint
          command: yarn lint

  ##
  # Weekly workflow: Audit
  ##
  audit:
    executor:
      name: default
    steps:
      - checkout
      - restore_packages
      - run:
          name: Run a security audit
          command: yarn audit

workflows:
  commit:
    jobs:
      # Phase 1: Setup
      - setup

      # Phase 2: Lint + audit
      - lint:
          requires:
            - setup

      - audit:
          requires:
            - setup
